import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDescriptionToSubject1748892945563 implements MigrationInterface {
    name = 'AddDescriptionToSubject1748892945563'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "course_participant" DROP CONSTRAINT "course_participant_courseId_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP CONSTRAINT "course_participant_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "checklist_item" DROP CONSTRAINT "checklist_item_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "subjects_teacher_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "conferences" DROP CONSTRAINT "conferences_host_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "users_groups_group_groupId_fkey"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "users_groups_group_usersId_fkey"`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" DROP CONSTRAINT "FK_users_followers_users_users_2"`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" DROP CONSTRAINT "FK_users_followers_users_users_1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_item_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_followers_users_users_1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_followers_users_users_2"`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "media" character varying, "likesCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "authorId" uuid, "postId" uuid, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "media" text, "poll" json, "likesCount" integer NOT NULL DEFAULT '0', "commentsCount" integer NOT NULL DEFAULT '0', "retweetsCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "authorId" uuid, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP, "location" character varying, "participantsCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "groupId" uuid, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "list" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" uuid, CONSTRAINT "PK_d8feafd203525d5f9c37b3ed3b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_864528ec4274360a40f66c29845" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "senderId" uuid, "conversationId" uuid, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lecture" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "content" text, "videoUrl" character varying, "slidesUrl" character varying, "order" integer NOT NULL, "courseId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2abef7c1e52b7b58a9f905c9643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assignment_type_enum" AS ENUM('homework', 'quiz', 'project', 'exam')`);
        await queryRunner.query(`CREATE TYPE "public"."assignment_status_enum" AS ENUM('draft', 'published', 'closed')`);
        await queryRunner.query(`CREATE TABLE "assignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "type" "public"."assignment_type_enum" NOT NULL DEFAULT 'homework', "status" "public"."assignment_status_enum" NOT NULL DEFAULT 'draft', "dueDate" TIMESTAMP, "maxScore" integer, "instructions" text, "submissionInstructions" text, "courseId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43c2f5a3859f54cedafb270f37e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "subject_id" uuid NOT NULL, CONSTRAINT "PK_0ef25918f0237e68696dee455bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "path" character varying NOT NULL, "mimetype" character varying NOT NULL, "size" integer NOT NULL, "lesson_id" integer NOT NULL, "uploaded_by" uuid NOT NULL, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('like', 'retweet', 'comment', 'follow')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."notification_type_enum" NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "recipientId" uuid, "actorId" uuid, "postId" uuid, "commentId" uuid, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "meeting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "scheduled_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "hostId" uuid, CONSTRAINT "PK_dccaf9e4c0e39067d82ccc7bb83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment_likes_users" ("commentId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_ff14357a755defa70edf6347c83" PRIMARY KEY ("commentId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a69c9d98bcc980f3f8f581f35" ON "comment_likes_users" ("commentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9e17fe8b26d1ca670190a2252" ON "comment_likes_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "post_likes_users" ("postId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_a36a67a784bc8eb725fa998bab2" PRIMARY KEY ("postId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_879c8ea4691cb1bcfa756da66f" ON "post_likes_users" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4df4b3e4af054986d1401a3c1" ON "post_likes_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "post_retweets_users" ("postId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_8118172d0f05e10bdd5f373a52c" PRIMARY KEY ("postId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e8079b6eeb978f03fa1c1d13ba" ON "post_retweets_users" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0926af1ea3ea0b2df258e111d2" ON "post_retweets_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "event_participants_users" ("eventId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_126c441f5fd5d5afbce2b16afa0" PRIMARY KEY ("eventId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_070f32efd23444c67cbdcfd7eb" ON "event_participants_users" ("eventId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc9ce124e2c6cd817c0fb23812" ON "event_participants_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "group_members_users" ("groupId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_63178ed1626de58e230f11b2e96" PRIMARY KEY ("groupId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d545245e94a265ba1e9517073d" ON "group_members_users" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0478f31b18047cc5adbc6174a4" ON "group_members_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "group_moderators_users" ("groupId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_b3733ba7b1b25cc08e08d341a86" PRIMARY KEY ("groupId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1ba00df3b77c603bbaa284a0d" ON "group_moderators_users" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf5feacd4f703384ce6804df9b" ON "group_moderators_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "list_users_users" ("listId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_a178fbb064cb3567ebeb1d44dd4" PRIMARY KEY ("listId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_368d3ba9fe14e2f729e8d109c2" ON "list_users_users" ("listId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aec10578b3a1a13033c79be73e" ON "list_users_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "conversation_participants_users" ("conversationId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_9f1c273ed200008aaf268bd2f46" PRIMARY KEY ("conversationId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c03448affaa46a025440e3932" ON "conversation_participants_users" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a236e54f2eb0a63a9527349b5d" ON "conversation_participants_users" ("usersId") `);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "duration"`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "membersCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "group" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "group_pkey"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."course_participant_role_enum" AS ENUM('teacher', 'student')`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD "role" "public"."course_participant_role_enum" NOT NULL DEFAULT 'student'`);
        await queryRunner.query(`ALTER TABLE "checklist_item" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "checklist_item" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklist_item" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "role_name_key"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "name"`);
        await queryRunner.query(`CREATE TYPE "public"."role_name_enum" AS ENUM('admin', 'teacher', 'student')`);
        await queryRunner.query(`ALTER TABLE "role" ADD "name" "public"."role_name_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_nickname_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "nickname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_ad02a1be8707004cb805a4b5023" UNIQUE ("nickname")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_group"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_group" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "about"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "about" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "banner"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "banner" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conferences" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "conferences" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "room_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "room_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "room_name" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "users_groups_group_pkey"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "users_groups_group_pkey" PRIMARY KEY ("usersId")`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD "groupId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "users_groups_group_pkey"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "users_groups_group_pkey" PRIMARY KEY ("usersId", "groupId")`);
        await queryRunner.query(`CREATE INDEX "IDX_8a8d151561d34fb00229f76a32" ON "users_groups_group" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_edb469b8953050465bd0ca165b" ON "users_groups_group" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d63f6043394b4d32343bdea11" ON "users_followers_users" ("usersId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_1433e3275a501bc09f5c33c7ca" ON "users_followers_users" ("usersId_2") `);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_276779da446413a0d79598d4fbd" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_94a85bb16d24033a2afdd5df060" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_0a28dcf5832d1068df34fc59e46" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "list" ADD CONSTRAINT "FK_f0f290e54e6663b786fe5a8134f" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_bc096b4e18b1f9508197cd98066" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f" FOREIGN KEY ("conversationId") REFERENCES "conversation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lecture" ADD CONSTRAINT "FK_89e61e55d5b02ea76363a3a55a6" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment" ADD CONSTRAINT "FK_5218258c0784c8b47c5079b8198" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD CONSTRAINT "FK_0706cd0ed95647dc47334cacc4c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD CONSTRAINT "FK_3f102e96e37ebf13cb2ac5835ef" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_item" ADD CONSTRAINT "FK_8c947450b10b06b323ff46bde42" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson" ADD CONSTRAINT "FK_aeaae22f4d629e1df4e54ca9695" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file" ADD CONSTRAINT "FK_f7f35484c24dc8b05d77c5178b0" FOREIGN KEY ("lesson_id") REFERENCES "lesson"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file" ADD CONSTRAINT "FK_7b877394007233a988b1b845378" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_ab7cbe7a013ecac5da0a8f88884" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_c5133a026bd1b3d9feccac1a234" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_c7dc378ca2844fdfe647e00e993" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_8dcb425fddadd878d80bf5fa195" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conferences" ADD CONSTRAINT "FK_a65612d511d8f59df3d4b86d05a" FOREIGN KEY ("host_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting" ADD CONSTRAINT "FK_cad9f9392de84ea417ff7cce375" FOREIGN KEY ("hostId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_likes_users" ADD CONSTRAINT "FK_2a69c9d98bcc980f3f8f581f35a" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_likes_users" ADD CONSTRAINT "FK_b9e17fe8b26d1ca670190a2252f" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_likes_users" ADD CONSTRAINT "FK_879c8ea4691cb1bcfa756da66fb" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_likes_users" ADD CONSTRAINT "FK_a4df4b3e4af054986d1401a3c1e" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_retweets_users" ADD CONSTRAINT "FK_e8079b6eeb978f03fa1c1d13ba4" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_retweets_users" ADD CONSTRAINT "FK_0926af1ea3ea0b2df258e111d2c" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event_participants_users" ADD CONSTRAINT "FK_070f32efd23444c67cbdcfd7ebb" FOREIGN KEY ("eventId") REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event_participants_users" ADD CONSTRAINT "FK_bc9ce124e2c6cd817c0fb238120" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "group_members_users" ADD CONSTRAINT "FK_d545245e94a265ba1e9517073d8" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "group_members_users" ADD CONSTRAINT "FK_0478f31b18047cc5adbc6174a47" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "group_moderators_users" ADD CONSTRAINT "FK_b1ba00df3b77c603bbaa284a0d6" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "group_moderators_users" ADD CONSTRAINT "FK_cf5feacd4f703384ce6804df9b7" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "list_users_users" ADD CONSTRAINT "FK_368d3ba9fe14e2f729e8d109c2e" FOREIGN KEY ("listId") REFERENCES "list"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "list_users_users" ADD CONSTRAINT "FK_aec10578b3a1a13033c79be73e8" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants_users" ADD CONSTRAINT "FK_5c03448affaa46a025440e39329" FOREIGN KEY ("conversationId") REFERENCES "conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants_users" ADD CONSTRAINT "FK_a236e54f2eb0a63a9527349b5d6" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "FK_8a8d151561d34fb00229f76a325" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "FK_edb469b8953050465bd0ca165b9" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" ADD CONSTRAINT "FK_8d63f6043394b4d32343bdea11d" FOREIGN KEY ("usersId_1") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" ADD CONSTRAINT "FK_1433e3275a501bc09f5c33c7ca2" FOREIGN KEY ("usersId_2") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_followers_users" DROP CONSTRAINT "FK_1433e3275a501bc09f5c33c7ca2"`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" DROP CONSTRAINT "FK_8d63f6043394b4d32343bdea11d"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "FK_edb469b8953050465bd0ca165b9"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "FK_8a8d151561d34fb00229f76a325"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants_users" DROP CONSTRAINT "FK_a236e54f2eb0a63a9527349b5d6"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants_users" DROP CONSTRAINT "FK_5c03448affaa46a025440e39329"`);
        await queryRunner.query(`ALTER TABLE "list_users_users" DROP CONSTRAINT "FK_aec10578b3a1a13033c79be73e8"`);
        await queryRunner.query(`ALTER TABLE "list_users_users" DROP CONSTRAINT "FK_368d3ba9fe14e2f729e8d109c2e"`);
        await queryRunner.query(`ALTER TABLE "group_moderators_users" DROP CONSTRAINT "FK_cf5feacd4f703384ce6804df9b7"`);
        await queryRunner.query(`ALTER TABLE "group_moderators_users" DROP CONSTRAINT "FK_b1ba00df3b77c603bbaa284a0d6"`);
        await queryRunner.query(`ALTER TABLE "group_members_users" DROP CONSTRAINT "FK_0478f31b18047cc5adbc6174a47"`);
        await queryRunner.query(`ALTER TABLE "group_members_users" DROP CONSTRAINT "FK_d545245e94a265ba1e9517073d8"`);
        await queryRunner.query(`ALTER TABLE "event_participants_users" DROP CONSTRAINT "FK_bc9ce124e2c6cd817c0fb238120"`);
        await queryRunner.query(`ALTER TABLE "event_participants_users" DROP CONSTRAINT "FK_070f32efd23444c67cbdcfd7ebb"`);
        await queryRunner.query(`ALTER TABLE "post_retweets_users" DROP CONSTRAINT "FK_0926af1ea3ea0b2df258e111d2c"`);
        await queryRunner.query(`ALTER TABLE "post_retweets_users" DROP CONSTRAINT "FK_e8079b6eeb978f03fa1c1d13ba4"`);
        await queryRunner.query(`ALTER TABLE "post_likes_users" DROP CONSTRAINT "FK_a4df4b3e4af054986d1401a3c1e"`);
        await queryRunner.query(`ALTER TABLE "post_likes_users" DROP CONSTRAINT "FK_879c8ea4691cb1bcfa756da66fb"`);
        await queryRunner.query(`ALTER TABLE "comment_likes_users" DROP CONSTRAINT "FK_b9e17fe8b26d1ca670190a2252f"`);
        await queryRunner.query(`ALTER TABLE "comment_likes_users" DROP CONSTRAINT "FK_2a69c9d98bcc980f3f8f581f35a"`);
        await queryRunner.query(`ALTER TABLE "meeting" DROP CONSTRAINT "FK_cad9f9392de84ea417ff7cce375"`);
        await queryRunner.query(`ALTER TABLE "conferences" DROP CONSTRAINT "FK_a65612d511d8f59df3d4b86d05a"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_8dcb425fddadd878d80bf5fa195"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_c7dc378ca2844fdfe647e00e993"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_c5133a026bd1b3d9feccac1a234"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_ab7cbe7a013ecac5da0a8f88884"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "file" DROP CONSTRAINT "FK_7b877394007233a988b1b845378"`);
        await queryRunner.query(`ALTER TABLE "file" DROP CONSTRAINT "FK_f7f35484c24dc8b05d77c5178b0"`);
        await queryRunner.query(`ALTER TABLE "lesson" DROP CONSTRAINT "FK_aeaae22f4d629e1df4e54ca9695"`);
        await queryRunner.query(`ALTER TABLE "checklist_item" DROP CONSTRAINT "FK_8c947450b10b06b323ff46bde42"`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP CONSTRAINT "FK_3f102e96e37ebf13cb2ac5835ef"`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP CONSTRAINT "FK_0706cd0ed95647dc47334cacc4c"`);
        await queryRunner.query(`ALTER TABLE "assignment" DROP CONSTRAINT "FK_5218258c0784c8b47c5079b8198"`);
        await queryRunner.query(`ALTER TABLE "lecture" DROP CONSTRAINT "FK_89e61e55d5b02ea76363a3a55a6"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_bc096b4e18b1f9508197cd98066"`);
        await queryRunner.query(`ALTER TABLE "list" DROP CONSTRAINT "FK_f0f290e54e6663b786fe5a8134f"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_0a28dcf5832d1068df34fc59e46"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_94a85bb16d24033a2afdd5df060"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_276779da446413a0d79598d4fbd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1433e3275a501bc09f5c33c7ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d63f6043394b4d32343bdea11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edb469b8953050465bd0ca165b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a8d151561d34fb00229f76a32"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "users_groups_group_pkey"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "users_groups_group_pkey" PRIMARY KEY ("usersId")`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD "groupId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" DROP CONSTRAINT "users_groups_group_pkey"`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "users_groups_group_pkey" PRIMARY KEY ("usersId", "groupId")`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "room_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "room_name" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "conferences" ALTER COLUMN "room_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conferences" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "conferences" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "banner"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "banner" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "about"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "about" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_group"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_group" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_ad02a1be8707004cb805a4b5023"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "nickname" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_nickname_key" UNIQUE ("nickname")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "title" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "UQ_ae4578dcaed5adff96595e61660"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "name"`);
        await queryRunner.query(`DROP TYPE "public"."role_name_enum"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "role_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "checklist_item" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checklist_item" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "checklist_item" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_participant" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."course_participant_role_enum"`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD "role" character varying NOT NULL DEFAULT 'student'`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "group" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "group_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "group" DROP COLUMN "membersCount"`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "teacher_id" uuid`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "duration" character varying`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "level" character varying`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "category" character varying`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "group" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "group" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a236e54f2eb0a63a9527349b5d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c03448affaa46a025440e3932"`);
        await queryRunner.query(`DROP TABLE "conversation_participants_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aec10578b3a1a13033c79be73e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_368d3ba9fe14e2f729e8d109c2"`);
        await queryRunner.query(`DROP TABLE "list_users_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf5feacd4f703384ce6804df9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1ba00df3b77c603bbaa284a0d"`);
        await queryRunner.query(`DROP TABLE "group_moderators_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0478f31b18047cc5adbc6174a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d545245e94a265ba1e9517073d"`);
        await queryRunner.query(`DROP TABLE "group_members_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc9ce124e2c6cd817c0fb23812"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_070f32efd23444c67cbdcfd7eb"`);
        await queryRunner.query(`DROP TABLE "event_participants_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0926af1ea3ea0b2df258e111d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8079b6eeb978f03fa1c1d13ba"`);
        await queryRunner.query(`DROP TABLE "post_retweets_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4df4b3e4af054986d1401a3c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_879c8ea4691cb1bcfa756da66f"`);
        await queryRunner.query(`DROP TABLE "post_likes_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9e17fe8b26d1ca670190a2252"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a69c9d98bcc980f3f8f581f35"`);
        await queryRunner.query(`DROP TABLE "comment_likes_users"`);
        await queryRunner.query(`DROP TABLE "meeting"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "lesson"`);
        await queryRunner.query(`DROP TABLE "assignment"`);
        await queryRunner.query(`DROP TYPE "public"."assignment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assignment_type_enum"`);
        await queryRunner.query(`DROP TABLE "lecture"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "conversation"`);
        await queryRunner.query(`DROP TABLE "list"`);
        await queryRunner.query(`DROP TABLE "event"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`CREATE INDEX "IDX_users_followers_users_users_2" ON "users_followers_users" ("usersId_2") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_followers_users_users_1" ON "users_followers_users" ("usersId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_item_userId" ON "checklist_item" ("userId") `);
        await queryRunner.query(`ALTER TABLE "users_followers_users" ADD CONSTRAINT "FK_users_followers_users_users_1" FOREIGN KEY ("usersId_1") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_followers_users" ADD CONSTRAINT "FK_users_followers_users_users_2" FOREIGN KEY ("usersId_2") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "users_groups_group_usersId_fkey" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_groups_group" ADD CONSTRAINT "users_groups_group_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conferences" ADD CONSTRAINT "conferences_host_id_fkey" FOREIGN KEY ("host_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "subjects_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_item" ADD CONSTRAINT "checklist_item_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD CONSTRAINT "course_participant_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_participant" ADD CONSTRAINT "course_participant_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
